#!/bin/bash

# Pistachio Linux's update script
# Licenced under GPLv3
VERSION="1.0.4"

# Help function

ShowHelp() 
{
    echo "pistachio-update allows you to update all components of Pistachio Linux."
    echo ""
    echo "Usage: pistachio-update"
}

if [ "$1" == "help" ]; then
    ShowHelp
    exit 0
fi

if [ "$1" == "version" ]; then
    echo "pistachio-update version $VERSION"
    exit 0
fi

# Check if the script is being run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root. (sudo pistachio-update)"
    exit 1
fi

# Check if the latest version is installed

echo "Checking pistachio-update version"

LATEST_UPDATE_VERSION=$(curl -s https://raw.githubusercontent.com/PistachioLinux/pistachio-scripts/master/pistachio-update | grep -m1 "VERSION=" | cut -d "=" -f 2 | tr -d '"')

VERSION=$(pistachio-update version | cut -d " " -f 3)

if [ "$LATEST_UPDATE_VERSION" == "$VERSION" ]; then
    echo "pistachio-update is up to date."
else
    echo "pistachio-update is not up to date. Updating..."
    curl -s https://raw.githubusercontent.com/PistachioLinux/pistachio-scripts/master/pistachio-update > /usr/bin/pistachio-update
    echo "pistachio-update updated. Please run pistachio-update again."
    exit 0
fi

echo "Checking pistachio-manager version"

# Check if pistachio-manager is installed
if [ ! -f /usr/bin/pistachio-manager ]; then
    echo "pistachio-manager isn't installed. Installing..."
    curl -s https://raw.githubusercontent.com/PistachioLinux/pistachio-scripts/master/pistachio-manager > /usr/bin/pistachio-manager
else
    # Get latest version of latest version of pistachio-manager
    LATEST_VERSION=$(curl -s https://raw.githubusercontent.com/PistachioLinux/pistachio-scripts/master/pistachio-manager | grep "VERSION=" | cut -d "=" -f 2 | tr -d '"')

    VERSION=$(pistachio-manager version | cut -d " " -f 3)

    # Check if the latest version is installed

    if [ "$LATEST_VERSION" == "$VERSION" ]; then
        echo "pistachio-manager is up to date."
    else
        echo "pistachio-manager is not up to date. Updating..."
        curl -s https://raw.githubusercontent.com/PistachioLinux/pistachio-scripts/master/pistachio-manager > /usr/bin/pistachio-manager
        echo "pistachio-manager updated."
    fi
fi

echo "Updating motd"

curl -s https://raw.githubusercontent.com/PistachioLinux/rootfs/master/files/motd > /etc/motd

echo "motd updated."